export const THEAD = [
    '#',
    'Update',
    'Kind Achtenaam',
    'Kind Voornaam',
    'Saldo',
    'Social',
    'Kind Geboortedatum',
    'School',
    'Level',
    'Kind Paspartoenummer',
    'Straatnaam en huisnummer',
    'PostCode en Gemeente',
    'Ouder Naam: 1',
    'Ouder Familienaam: 1',
    'Ouder Tel: 1',
    'Ouder Email: 1',
    'Ouder Naam: 2',
    'Ouder Familienaam: 2',
    'Ouder Tel: 2',
    'Ouder Email: 2',
    'Ouder RN',
    'Ouder Geboortedatum',
    'Kind RN',
    'Kind Allergieën',
    'Opmerkingen ouders',
    'Opmerkingen pleinleiding',
    'Medische Fiche',
    'Week 1',
    'Week 2',
    'Week 3',
    'Week 4',
    '',
  ];
